project:
  type: website

book:
  title: "Financial Report"
  author: "arhgreen"
  date: "2025-02-26"
  chapters: 
    - report.qmd
format:
  pdf:
    keep-md: true
    output-file: "Financial_Report.pdf"